---
- name: Install Docker and run a container
  hosts: barista
  become: yes

  tasks:
    - name: Update apt package cache and install dependencies
      become: true
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
    - name: Add Docker GPG Key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker repository
      become: true
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
    - name: Update apt and install Docker
      become: true
      apt:
        name: docker-ce
        state: present
        update_cache: yes
    - name: Pull Docker image
      become: true
      docker_image:
        name: balaji230792/baristaimg:v1  # Replace with your Docker image name and tag
        source: pull

    - name: Run Docker container
      become: true
      docker_container:
        name: Barista_Cafe # Replace with your desired container name
        image: balaji230792/baristaimg:v1  # Replace with your Docker image name and tag
        state: started
        restart_policy: always
        ports:
          - "7090:80"  # Replace with your desired port mappings